{{- if .Values.imagePullSecret.enabled }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .Values.imagePullSecret.name | default "ghcr-imagepull-secret" }}
  labels:
    {{- include "push-balancer.labels" . | nindent 4 }}
spec:
  refreshInterval: {{ .Values.imagePullSecret.refreshInterval | default "5m" }}
  secretStoreRef:
    name: {{ .Values.imagePullSecret.secretStoreRef.name }}
    kind: {{ .Values.imagePullSecret.secretStoreRef.kind | default "ClusterSecretStore" }}
  target:
    name: {{ .Values.imagePullSecret.name | default "ghcr-imagepull-secret" }}
    template:
      type: kubernetes.io/dockerconfigjson
      engineVersion: v2
      data:
        .dockerconfigjson: "{{`{{ .ghcrSecret | toString }}`}}"
    creationPolicy: Owner
  data:
    - secretKey: ghcrSecret
      remoteRef:
        key: {{ .Values.imagePullSecret.remoteRef.key }}
{{- end }}
